In [2]:
# !pip install cartopy
# !pip install geopandas
# !pip install xarray
# !pip install rioxarray
# !pip install shapely
# !pip install rasterio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.5/46.5 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 59.8 MB/s eta 0:00:0000:01:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 107.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 62.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 103.5 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 45.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.7/53.7 kB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.6/20.6 MB 77.9 MB/s eta 0:00:00:00:0100:01


In [1]:
# Importing the required libraries
import cartopy.crs as ccrs
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import xarray as xr
# import fsspec

from __future__ import absolute_import, division, print_function

import os

import tensorflow as tf
from tensorflow import keras
print("TensorFlow version is ", tf.__version__)

import numpy as np

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

2023-12-08 05:35:48.971489: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-08 05:35:49.919883: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/local/cuda/extras/CUPTI/lib64
2023-12-08 05:35:49.919984: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/loca

TensorFlow version is  2.11.0


In [2]:
# files paths
gcloud_bucket = "gs://satellite-tttr-hackathon"
satellite_path = "satellite"
weather_path = 'weather'

no2_files = gcloud_bucket+"/"+satellite_path+"/NO2/no2_kgm2_"
cl_files = gcloud_bucket+"/"+satellite_path+"/cloud_fraction/cloud_fraction_"

uwind_files = gcloud_bucket+"/"+weather_path+"/wind/uwind_ms_"
vwind_files = gcloud_bucket+"/"+weather_path+"/wind/vwind_ms_"

In [3]:
%%time
import gcsfs

# Create a GCSFileSystem object
fs = gcsfs.GCSFileSystem()

# Use wild-card matching to get a list of file paths
no2_paths = fs.glob(f'{no2_files}2023092*.tiff')

# Now, you can use the list of file paths as needed
no2_data = []
for file_path in no2_paths:
    wth = xr.open_dataarray("gs://"+file_path).values.reshape(241, 162)
    no2_data.append(wth)

# Use wild-card matching to get a list of file paths
uwind_paths = fs.glob(f'{uwind_files}2023092*.tiff')
uwind_data = []
for file_path in uwind_paths:
    wth = xr.open_dataarray("gs://"+file_path).values.reshape(241, 162)
    uwind_data.append(wth)

# Use wild-card matching to get a list of file paths
vwind_paths = fs.glob(f'{vwind_files}2023092*.tiff')
vwind_data = []
for file_path in vwind_paths:
    wth = xr.open_dataarray("gs://"+file_path).values.reshape(241, 162)
    vwind_data.append(wth)
    
all_data = [np.stack([n, u, v], axis=2) for n, u, v in zip(no2_data, uwind_data, vwind_data)]

CPU times: user 915 ms, sys: 102 ms, total: 1.02 s
Wall time: 30.4 s


In [4]:
np.array(all_data).shape

(10, 241, 162, 3)

In [192]:
array1 = np.random.rand(2,1,3,2)
array2 = np.random.rand(2,1,3,2)
array3 = np.random.rand(2,1,3,2)

print(array1)
print(array2)
print(array3)

[[[[0.34048816 0.46629883]
   [0.89606718 0.50672193]
   [0.6140323  0.23895174]]]


 [[[0.51053737 0.47284032]
   [0.10348238 0.04581285]
   [0.06684138 0.13765047]]]]
[[[[0.13565475 0.06106536]
   [0.59851379 0.23318968]
   [0.08123756 0.95020408]]]


 [[[0.15008507 0.30033946]
   [0.05435677 0.74956715]
   [0.0681632  0.18296753]]]]
[[[[0.87063523 0.04747422]
   [0.7665721  0.15367384]
   [0.23364717 0.63346679]]]


 [[[0.38946048 0.39327287]
   [0.41674752 0.20554518]
   [0.94956223 0.09229452]]]]


In [8]:
labels = pd.read_csv(gcloud_bucket+'/Taiwan_nox_emissions.csv')
labels = labels[(labels['facility_id']=='C1400170')&
                (labels['datetime']>='2023-09-20')&
                (labels['datetime']<'2023-09-30')]
labels

facility_id    datetime        value data_source poll unit
1546    C1400170  2023-09-20  6994.068441      tw_epa  nox   kg
1547    C1400170  2023-09-21  6669.730216      tw_epa  nox   kg
1548    C1400170  2023-09-22  6515.035139      tw_epa  nox   kg
1549    C1400170  2023-09-23  5882.552661      tw_epa  nox   kg
1550    C1400170  2023-09-24  3445.696530      tw_epa  nox   kg
1551    C1400170  2023-09-25  6289.207533      tw_epa  nox   kg
1552    C1400170  2023-09-26  4833.342712      tw_epa  nox   kg
1553    C1400170  2023-09-27  5003.181407      tw_epa  nox   kg
1554    C1400170  2023-09-28  6007.419708      tw_epa  nox   kg
1555    C1400170  2023-09-29  3614.927075      tw_epa  nox   kg

In [14]:
from keras.applications import ResNet50
from keras.models import Model
from keras.layers import Dense, GlobalAveragePooling2D
from keras.optimizers import Adam
from keras.preprocessing.image import ImageDataGenerator

image_size = all_data[0].shape

# Load the ResNet50 model without the top (fully connected) layers
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=all_data[0].shape)

# Freeze the layers of the base model
for layer in base_model.layers:
    layer.trainable = False

# Add your regression head
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
predictions = Dense(1, activation='linear')(x)

# Create the final model
model = Model(inputs=base_model.input, outputs=predictions)

# Compile the model
# model.compile(optimizer=Adam(), loss='mean_squared_error')  # Use appropriate loss for regression task
model.compile(loss='mean_squared_error')  # Use appropriate loss for regression task

# Print the model summary
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_2 (InputLayer)           [(None, 241, 162, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv1_pad (ZeroPadding2D)      (None, 247, 168, 3)  0           ['input_2[0][0]']                
                                                                                                  
 conv1_conv (Conv2D)            (None, 121, 81, 64)  9472        ['conv1_pad[0][0]']              
                                                                                                  
 conv1_bn (BatchNormalization)  (None, 121, 81, 64)  256         ['conv1_conv[0][0]']       

In [28]:
np.nan_to_num(all_data, nan=0)

array([[[[ 7.24307372e-07,  2.51184607e+00, -1.46337128e+00],
         [ 7.52984732e-07,  2.41739464e+00, -1.44679070e+00],
         [ 8.10482764e-07,  2.32277489e+00, -1.43003011e+00],
         ...,
         [ 7.39154267e-07, -1.03873134e+00,  4.93904686e+00],
         [ 6.99387998e-07, -1.01356661e+00,  4.89795637e+00],
         [ 6.45829380e-07, -9.97628927e-01,  4.85902786e+00]],

        [[ 6.98359197e-07,  2.47074366e+00, -1.45309854e+00],
         [ 6.92541238e-07,  2.37629223e+00, -1.43651819e+00],
         [ 7.50457896e-07,  2.28184032e+00, -1.41975737e+00],
         ...,
         [ 7.23876736e-07, -1.06238616e+00,  4.91147280e+00],
         [ 6.20021041e-07, -1.03722143e+00,  4.87038231e+00],
         [ 6.03408142e-07, -1.02145159e+00,  4.83145380e+00]],

        [[ 9.38152779e-07,  2.42947340e+00, -1.44246554e+00],
         [ 8.84679587e-07,  2.33502197e+00, -1.42588496e+00],
         [ 7.63953093e-07,  2.24057007e+00, -1.40930438e+00],
         ...,
         [ 4.84147396e-0

In [29]:
# x_train = np.array(all_data)
x_train = np.nan_to_num(all_data, nan=0)
y_train = np.array(labels.value)

# Create an ImageDataGenerator for data augmentation and normalization
datagen = ImageDataGenerator(validation_split=0)

# Training data generator
train_generator = datagen.flow(x_train, y_train, subset='training', 
                               ignore_class_split=True)

# Train the model
model.fit(train_generator, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 73ms/step - loss: nan
Epoch 2/10
1/1 [==============================] - 0s 70ms/step - loss: nan
Epoch 3/10
1/1 [==============================] - 0s 69ms/step - loss: nan
Epoch 4/10
1/1 [==============================] - 0s 60ms/step - loss: nan
Epoch 5/10
1/1 [==============================] - 0s 63ms/step - loss: nan
Epoch 6/10
1/1 [==============================] - 0s 57ms/step - loss: nan
Epoch 7/10
1/1 [==============================] - 0s 62ms/step - loss: nan
Epoch 8/10
1/1 [==============================] - 0s 65ms/step - loss: nan
Epoch 9/10
1/1 [==============================] - 0s 61ms/step - loss: nan
Epoch 10/10
1/1 [==============================] - 0s 57ms/step - loss: nan


In [ ]:
predictions = model.predict(x_train)

# Print the regression output
print("Regression Output:", predictions)